# Playbook to create a droplet in Digital Ocean
# ---------------------------------------------
#
# These environment variables should be populated:
#       DO_CLIENT_ID (api v1)
#       DO_API_KEY (api v1)
#       DO_API_TOKEN (api v2)
#
- hosts: localhost
  connection: local
  vars:
    username: alex
    domain: lekum.org
    authorized_ssh_keys:
      - "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    droplet_name: riemann
    do_region_id: lon1
    do_image_id: ubuntu-15-04-x64
    do_size_id: 512mb

  tasks:

    - name: Template out the cloud-config.yml file
      template:
        src: templates/cloud-config.yml.j2
        dest: ./cloud-config.yml

    - name: Create the DigitalOcean droplet
      digital_ocean:
        state: present
        command: droplet
        name: "{{ droplet_name }}"
        region_id: "{{ do_region_id }}"
        size_id: "{{ do_size_id }}"
        image_id: "{{ do_image_id }}"
        user_data: "{{ lookup('file', 'cloud-config.yml') }}"
        unique_name: yes
      register: do_result

    - name:  Associate the domain with the droplet
      digital_ocean_domain: state=present name={{ domain }} ip={{ do_result.droplet.ip_address }}
